name: release-packages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
          id: go

      - name: Install dependencies
        run: |
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get install -y libgtk-3-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev libsdl2-dev libasound2-dev > /dev/null 2>&1
          sudo apt-get install -y xvfb
          sudo apt-get install -y mingw-w64

      - name: Build .bin package
        run: |
          go build -o singen.bin .

      - name: Build .exe package
        run: |
          CGO_ENABLED="1" GOOS="windows"  CC="/usr/bin/x86_64-w64-mingw32-gcc" CXX="/usr/bin/x86_64-w64-mingw32-c++" go build -o singen.exe .

      - uses: "marvinpinto/action-automatic-releases@v1.2.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            singen.bin
            singen.exe
